In [1]:
import numpy as np
import matplotlib.pyplot as plt
import h5py
import cv2

import mediapipe as mp
from mediapipe.framework.formats import landmark_pb2
from mediapipe import solutions

In [2]:
## 1. IMAGES
h5f = h5py.File('datasets/data_train_images.h5','r')
train_images = h5f['data_train_images'][:]
h5f.close()

## 2. LANDMARKS
h5f = h5py.File('datasets/data_train_landmarks.h5','r')
train_landmarks = h5f['data_train_landmarks'][:]
h5f.close()

## 3. LABELS
h5f = h5py.File('datasets/data_train_labels.h5','r')
train_labels = h5f['data_train_labels'][:]
h5f.close()


## display the size of the different data tables
print("> Images")
print('Number of training images     :', train_images.shape[0])
print('Number of frames per sequence :', train_images.shape[1])
print('Image shape                   :', train_images[0][0].shape)

print("\n> Landmarks")
print('Number of landmarks in a face      :', train_landmarks.shape[2])
print('Number of coordinates per landmark :', train_landmarks.shape[-1])


print("\n> Labels")
print('Number of training labels:', train_labels.shape[0])

> Images
Number of training images     : 486
Number of frames per sequence : 10
Image shape                   : (200, 200)

> Landmarks
Number of landmarks in a face      : 478
Number of coordinates per landmark : 3

> Labels
Number of training labels: 486


In [3]:
print(train_landmarks)

[[[[ 0.51720852  0.64851046 -0.10767879]
   [ 0.52070361  0.53869706 -0.19684373]
   [ 0.51756066  0.57504094 -0.10321452]
   ...
   [ 0.6829986   0.30323285  0.03852873]
   [ 0.64550829  0.3314389   0.03848623]
   [ 0.6824621   0.36073545  0.03849398]]

  [[ 0.52008158  0.65140051 -0.10564421]
   [ 0.52180988  0.54209149 -0.19616714]
   [ 0.51903766  0.57805955 -0.10197118]
   ...
   [ 0.68727034  0.30316442  0.03586097]
   [ 0.64949888  0.33177403  0.03581925]
   [ 0.68648756  0.36121994  0.03582682]]

  [[ 0.51443738  0.65150255 -0.10762052]
   [ 0.51950097  0.54027057 -0.19635074]
   [ 0.51596737  0.57712591 -0.10307002]
   ...
   [ 0.68502694  0.30219942  0.03744185]
   [ 0.64797705  0.33085799  0.03739803]
   [ 0.68474233  0.35991675  0.03740586]]

  ...

  [[ 0.51111889  0.63370013 -0.11316786]
   [ 0.51915389  0.53254658 -0.20213787]
   [ 0.51521969  0.56657714 -0.10842961]
   ...
   [ 0.69351792  0.30399245  0.03960473]
   [ 0.65947032  0.32826239  0.03955882]
   [ 0.69347644 